# Generated by Django 3.0.7 on 2020-08-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200812_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='date_added',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='state',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zipcode',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
